'use strict';

module.exports = {
  extends: [
    'eslint:recommended',
    'prettier',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:node/recommended',
  ],
  plugins: ['import'],
  parserOptions: {
    sourceType: 'module',
  },
  env: {
    es6: true,
    node: true,
  },
  rules: {
    indent: ['error', 2, { SwitchCase: 1 }],
    'linebreak-style': ['error', 'unix'],
    'no-console': 'error',
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'object-curly-spacing': ['error', 'always'],
    'prefer-const': ['error', { destructuring: 'all' }],
    'no-var': 'error',
    'dot-notation': 'error',
    eqeqeq: 'error',
    'no-multi-spaces': 'error',
    'prefer-regex-literals': 'error',
    'prefer-promise-reject-errors': 'error',
    'array-bracket-newline': ['error', 'consistent'],
    'block-spacing': 'error',
    'brace-style': 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'arrow-parens': ['error', 'always'],
    'quote-props': ['error', 'as-needed'],
    'no-trailing-spaces': 'error',
    'require-atomic-updates': 'off',
    'no-process-exit': 'off',
    strict: ['error', 'global'],
    'import/order': 'error',
    'import/no-cycle': 'error',
    'import/no-useless-path-segments': 'error',
    'import/first': 'error',
    'import/extensions': ['error', 'always'],
    'import/newline-after-import': 'error',
    'node/no-callback-literal': 'error',
    'node/no-path-concat': 'error',
    'node/no-unsupported-features/es-syntax': ['error', { ignores: ['modules'] }],
    'node/handle-callback-err': 'error',
    'one-var': ['error', 'never'],
  },
};
